services:
  bot:
    container_name: bot
    build: ./Dockerfile
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DEBUG=$DEBUG
    ports:
    - 2332:2332
    develop:
      watch:
        - action: sync
          path: .
          target: /bot
        - action: rebuild 
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 3s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4:9.11
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data: